# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=10)),
                ('nickName', models.CharField(max_length=20)),
                ('surName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
